<nav class="navbar navbar-default no-border br-b-yeello" role="navigation">
    <div class="container-fluid no-padding">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header no-margin">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <span class="pull-left bg-yellow" style="width:15px; height:50px;"></span>
            <a class="navbar-brand p-10" href="<?php echo $this->basepath();?>/">Real Estate</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse no-margin" id="bs-example-navbar-collapse-1">

            <ul class="nav navbar-nav navbar-right p-10-0 bg-yellow c-white">
                <li>
                    <div class="dropdown">
                        <span class="dropdown-toggle p-5-10" style="display:inline-block; cursor: pointer;" id="dropdownMenu1" data-toggle="dropdown"><i class="glyphicon glyphicon-th"></i> Menu</span>
                        <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">
                            <li role="presentation"><a role="menuitem" tabindex="-1" href="<?php echo $this->basepath();?>/all-property">All Properties</a></li>
                            <li role="presentation"><a role="menuitem" tabindex="-1" href="<?php echo $this->basepath();?>/addnew">Add new property</a></li>
                            <li role="presentation" class="divider"></li>
                            <li role="presentation"><a role="menuitem" tabindex="-1" href="<?php echo $this->basepath();?>/user-management">User management</a></li>
                            <li role="presentation"><a role="menuitem" tabindex="-1" href="<?php echo $this->basepath();?>/user-add">Add new user</a></li>
                            <li role="presentation" class="divider"></li>
                            <li role="presentation"><a role="menuitem" tabindex="-1" href="<?php echo $this->basepath();?>/report">Report management</a></li>
                        </ul>
                    </div>
                </li>

                <li><a href="<?php echo $this->basepath();?>/logout">Logout</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right p-10-0 bg-dark-yellow c-white">
                <li><a  href="<?php echo $this->basepath('/advance-search');?>">Advance</a></li>
            </ul>
            <form class="navbar-form navbar-right" role="search" action="<?php echo $this->basepath();?>/all-property">
                <div class="form-group">
                    <input name="s" type="text" class="form-control" placeholder="Search" value="<?php echo $this->searchText; ?>">
                </div>
                <button type="submit" class="btn btn-default"><i class="glyphicon glyphicon-search"></i></button>
            </form>

        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>