<?php echo $this->doctype(); ?>

<html lang="en" ng-app>
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle($this->translate('Real Estate Management System - Anco'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-responsive.min.css')
                        ->prependStylesheet($this->basePath() . '/css/global.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                                      ->prependFile($this->basePath() . '/js/bootstrap.min.js')
                                      ->prependFile($this->basePath() . '/js/jquery.min.js') ?>

    </head>
    <body class="no-padding">
        <!-- START BLOCK OF HEADER -->
        <header>
            <?php echo $this->partial("layout/_header"); ?>
        </header>
        <!-- END BLOCK OF HEADER -->


        <!-- START BLOCK OF BODY -->
        <div class="w-center clearfix" style="margin-bottom:70px;">
            <?php echo $this->content; ?>
        </div>
        <!-- END BLOCK OF BODY -->


        <!-- START BLOCK OF FOOTER -->
        <footer class="fixed-bottom p-10-15 bg-gray full-w br-t-yellow" >
            <p>&copy; 2005 - <?php echo date('Y') ?> by ANCO BROTHERS CO., LTD.. <?php echo $this->translate('All rights reserved.') ?></p>
        </footer>
        <!-- END BLOCK OF FOOTER -->


        <?php echo $this->inlineScript() ?>
    </body>
</html>
