
    <h4 class="m-15-0 p-15-0">General Information</h4>
    <div class="clearfix">
        <aside class="col-md-8">
            <div class="form-group">
                <label>Title: <i class="c-red">*</i></label>
                <input name="prop_name" required=""  type="text" class="form-control" id="" placeholder="title" ng-model="p.prop_name">
            </div>
        </aside>
        <aside class="col-md-4">
            <div class="form-group">
                <label>Code number
                    : <i class="c-red"></i></label>
                <input name="prop_code"   type="text" class="form-control" id="" placeholder="code number" ng-model="p.prop_code">
            </div>
        </aside>
    </div>
    <div class="clearfix">
        <aside class="col-md-4">
            <div class="form-group">
                <label for="">Province / City: <i class="c-red">*</i></label>
                <select
                    ng-options="prov.province_id as prov.prov_name for prov in provinces"
                    name="province_id"
                    class="form-control"
                    ng-model="p.province_id" required="" ng-change="provinceChange()">

                </select>
            </div>
        </aside>
        <aside class="col-md-4">
            <div class="form-group">
                <label for="">Location:</label>
                <input  name="prop_location"  type="text" class="form-control" id="" placeholder="location" ng-model="p.prop_location" />
            </div>
        </aside>
        <aside class="col-md-4">
            <div class="form-group">
                <label for="">Address:</label>
                <input name="prop_address" type="text" class="form-control" id="" placeholder="Address" ng-model="p.prop_address" />
            </div>
        </aside>
    </div>

    <div class="clearfix">
        <aside class="col-md-4">
            <div class="form-group">
                <label for="">Land dimension: <i class="c-red">*</i></label>
                <input name="prop_dimension" ng-model="p.prop_dimension"  type="text" class="form-control" id="" placeholder="land dimension" required="" />
            </div>
        </aside>
        <aside class="col-md-4">
            <div class="col-md-6 no-padding-left">
                <div class="form-group">
                    <label for="">Size of land: <i class="c-red">*</i></label>
                    <input name="prop_size" ng-model="p.prop_size" type="text" class="form-control" id="" placeholder="size of land" required=""/>
                </div>    
            </div>
            <div class="col-md-6 no-padding-right">
                <div class="form-group">
                    <label for="">Land size by google:</label>
                    <input disabled name="polygon_size" ng-model="p.polygon_size" type="text" class="form-control" id="" placeholder="" value=""/>
                </div> 
            </div>
            
        </aside>
        <aside class="col-md-4">
            <div class="form-group">
                <label for="">Road type: </label>
                <input name="prop_road_type" ng-model="p.prop_road_type"  type="text" class="form-control" id="" placeholder="road type">
            </div>
        </aside>
    </div>

    <div class="clearfix">
        <div class="form-group col-md-12">
            <label> Property Description: </label>
            <textarea rows="8" name="prop_description" ng-model="p.prop_description" class="form-control"></textarea>
        </div>
    </div>
