<h4 class="m-15-0 p-15-0">
    Map of property
    <a class="btn btn-xs btn-clear btn-danger btn-clear-map"> <i class="glyphicon glyphicon-remove"></i> Clear</a>
    <span class="label label-info pull-right polygon-area">Area: {{p.polygon_size}} smq2</span></h4>
<div class="clearfix">
    <aside class="col-md-12">
        <div class="form-group">
            <div class="col-md-12" id="map-canvas" style=" width:100%; height:450px;"></div>
        </div>
    </aside>
</div>