<?php
/**
 * Created by PhpStorm.
 * User: dimang12
 * Date: 10/6/14
 * Time: 11:35 AM
 */
?>

<h4 class="m-15-0 p-15-0">Neighbouring</h4>

<div class="clearfix">
    <aside class="col-md-4">
        <div class="form-group">
            <label for="">North:</label>
            <input name="prop_north" ng-model="p.prop_north" type="text" class="form-control" id="" placeholder="North">
        </div>
    </aside>
    <aside class="col-md-4">
        <div class="form-group">
            <label for="">South:</label>
            <input name="prop_south" ng-model="p.prop_south" type="text" class="form-control" id="" placeholder="south">
        </div>
    </aside>
    <aside class="col-md-4">
        <div class="form-group">
            <label for="">East: </label>
            <input name="prop_east" ng-model="p.prop_east" type="text" class="form-control" id="" placeholder="east">
        </div>
    </aside>
</div>

<div class="clearfix">
    <aside class="col-md-4">
        <div class="form-group">
            <label for="">West:</label>
            <input name="prop_west" ng-model="p.prop_west" type="text" class="form-control" id="" placeholder="west">
        </div>
    </aside>
</div>