<?php
/**
 * Created by PhpStorm.
 * User: dimang12
 * Date: 10/6/14
 * Time: 11:58 AM
 */
?>


<h4 class="m-15-0 p-15-0">SWOT</h4>

<div class="clearfix">
    <aside class="col-md-12">
        <div class="form-group">
            <label for="">Strength:</label>
            <textarea rows="12" name="swot_strength" ng-model="p.swot_strength" class="form-control"></textarea>
        </div>
    </aside>

    <aside class="col-md-12">
        <div class="form-group">
            <label for="">Weakness:</label>
            <textarea rows="12" name="swot_weakness" ng-model="p.swot_weakness"  class="form-control"></textarea>
        </div>
    </aside>

    <aside class="col-md-12">
        <div class="form-group">
            <label for="">Opportunity:</label>
            <textarea rows="12" name="swot_opportunity" ng-model="p.swot_opportunity" class="form-control"></textarea>
        </div>
    </aside>

    <aside class="col-md-12">
        <div class="form-group">
            <label for="">Threat:</label>
            <textarea rows="12" name="swot_threat" ng-model="p.swot_threat" class="form-control"></textarea>
        </div>
    </aside>
</div>
