<div class="container" style="margin-top:100px;">
    <div class="col-md-6 col-md-offset-3">
        <div class="text-danger bg-gray br-gray">
            <p>
                <h4 class="text-center">
                    <br>
                    <i class="glyphicon glyphicon-warning-sign text-warning" style="font-size:60px;"></i><br><br>
                    Sorry, you haven't permission to access this page. <br>
                    back to <a href="<?php echo $this->basepath(); ?>/"> home </a> page.
                    <br><br>
                </h4>
            </p>
        </div>
    </div>
</div>