<?php
    use Application\Controller\Permission;
    $this->headScript ()
        ->prependFile ( 'https://maps.googleapis.com/maps/api/js?v=3.exp&libraries=drawing,geometry')
        ->prependFile ( $this->basepath() .'/js/gallery.js' )
    ;
    $this->headLink ()->prependStylesheet($this->basePath() . '/css/detail.css')
                      ->prependStylesheet($this->basePath() . '/css/image-preview.css')
    ;
    $p = $this->property[0];
    $polygon = $p["prop_polygon"];

?>
<div>
    <h2 class="font-24 br-b-yeello p-15-0 no-margin"><?php echo $p["prop_name"] ; if(!empty($p["prop_code"])) echo " (".$p["prop_code"].")";?>
        <span class="pull-right font-13 p-10-0">
            <a href="<?php echo $_SERVER["HTTP_REFERER"]; ?>"><i class="glyphicon glyphicon-chevron-left"></i> back</a>
            <label> &nbsp; | &nbsp; </label>
            <a href="<?php echo $this->basepath();?>/all-property?pid=<?php echo  $p["property_id"]."&page=" .$this->page ?>"><i class="glyphicon glyphicon-th-list"></i> View all</a>
            <?php if(Permission::getPermission()==true): ?>
            <label> &nbsp; | &nbsp; </label>
            <a href="<?php echo $this->basepath();?>/edit?pid=<?php echo $p["property_id"]; ?>" class=""><i class="glyphicon glyphicon-pencil"></i> Edit</a>
            <label> &nbsp; | &nbsp; </label>
            <a class="" href="<?php echo $this->basepath();?>/addnew"><i class="glyphicon glyphicon-plus"></i> Add New</a>
            <?php endif;?>
        </span>
    </h2>
    <div class="clearfix p-15-0 m-10-0">
        <aside class="col-md-8  no-padding-left">
            <div class="m-bottom-15 p-b-10 br-b-gray">
                <h3>Description</h3>
                <p>
                    <?php echo $p["prop_description"]; ?>
                </p>
            </div>

            <div class="m-bottom-15 p-b-10 br-b-gray clearfix detail">

                <aside class="col-md-6 no-padding-left">
                    <h3>Genderal Information</h3>
                    <p class="p-b-10">
                        <summary open="open" >

                            <article class="clearfix">
                                <label class="col-md-5">Province/City</label>
                                <span class="col-md-7">: <?php echo $p["prov_name"]; ?></span>
                            </article>
                            <article class="clearfix">
                                <label class="col-md-5">Location</label>
                                <span class="col-md-7">: <?php echo $p["prop_location"]; ?></span>
                            </article>
                            <article class="clearfix">
                                <label class="col-md-5">Address</label>
                                <span class="col-md-7">: <?php echo $p["prop_address"]; ?></span>
                            </article>
                            <article class="clearfix">
                                <label class="col-md-5">Land dimension</label>
                                <span class="col-md-7">: <?php echo $p["prop_dimension"]; ?></span>
                            </article>
                            <article class="clearfix">
                                <label class="col-md-5">Land size</label>
                                <span class="col-md-7">: <?php echo $p["prop_size"] . " m<sup>2</sup> (".$p["polygon_size"].")"; ?></span>
                            </article>
                            <article class="clearfix">
                                <label class="col-md-5">Road type</label>
                                <span class="col-md-7">: <?php echo $p["prop_road_type"]; ?></span>
                            </article>
                        </summary>
                    </p>
                </aside>

                <aside class="col-md-6 no-padding-left">
                    <h3>Pricing </h3>
                    <p class="p-b-10">
                        <summary open="open" >

                            <article class="clearfix">
                                <label class="col-md-5">Origional price</label>
                                <span class="col-md-7">: $ <?php echo $p["price_original"]; ?></span>
                            </article>
                            <article class="clearfix">
                                <label class="col-md-5">Price with tax</label>
                                <span class="col-md-7">: $ <?php echo $p["price_tax"]; ?></span>
                            </article>
                            <article class="clearfix">
                                <label class="col-md-5">Last year price</label>
                                <span class="col-md-7">: $ <?php echo $p["price_latest"]; ?></span>
                            </article>
                            <article class="clearfix">
                                <label class="col-md-5">Market price</label>
                                <span class="col-md-7">: $ <?php echo $p["price_market"]; ?></span>
                            </article>
                        </summary>
                    </p>
                </aside>
                <br><br>
            </div>


            <div class="m-bottom-15 p-b-10 br-b-gray clearfix detail">
                <aside class="col-md-6 no-padding-left">
                    <h3>Neighbouring Land</h3>
                    <p class="p-b-10">
                        <summary open="open" >

                            <article class="clearfix">
                                <label class="col-md-5">North</label>
                                <span class="col-md-7">: <?php echo $p["prop_north"]; ?></span>
                            </article>
                            <article class="clearfix">
                                <label class="col-md-5">South</label>
                                <span class="col-md-7">: <?php echo $p["prop_south"]; ?></span>
                            </article>
                            <article class="clearfix">
                                <label class="col-md-5">East</label>
                                <span class="col-md-7">: <?php echo $p["prop_east"]; ?></span>
                            </article>
                            <article class="clearfix">
                                <label class="col-md-5">West</label>
                                <span class="col-md-7">: <?php echo $p["prop_west"]; ?></span>
                            </article>
                        </summary>
                    </p>
                </aside>
                <aside class="col-md-6 no-padding-left">
                    <h3>Vision </h3>
                    <p class="p-b-10">
                        <summary open="open" >
                            <?php echo $p["prop_vision"] ?>
                        </summary>
                    </p>
                </aside>
                <br><br>
            </div>

            <div class="m-bottom-15 p-b-10 clearfix">
                <h3 class="p-b-10 ">Map</h3>
                <div class="col-md-12" id="map-canvas" style=" width:100%; height:300px;"></div>
            </div>

            <div class="m-bottom-15 p-b-10">
                <h3 class="br-b-gray p-b-10">SWOT</h3>
                <div class="clearfix">
                    <div class="col-md-12">
                        <label class="p-b-10 font-16">Strength</label>
                        <div class="col-md-12"><?php echo $p["swot_strength"]; ?></div>
                    </div>
                    <div class="col-md-12">
                        <label class="p-b-10 font-16">Weakness</label>
                        <div class="col-md-12"><?php echo $p["swot_weakness"]; ?></div>
                    </div>
                </div>
                <div class="clearfix">
                    <div class="col-md-12">
                        <label class="p-b-10 font-16">Opportunity</label>
                        <div class="col-md-12"><?php echo $p["swot_opportunity"]; ?></div>
                    </div>
                    <div class="col-md-12">
                        <label class="p-b-10 font-16">Threat</label>
                        <div class="col-md-12"><?php echo $p["swot_threat"]; ?></div>
                    </div>
                </div>



            </div>
        </aside>


        <aside class="col-md-4 br-radius-5 br-gray bg-gray p-5 gallery">

            <?php
            foreach($this->property as $k=>$v){
                if(!empty($v["img_file"]) && $v["img_type"]==1){

                    echo '<img width="100%" src="'.$this->basepath().'/images/files/'.$v["img_file"].'" alt="...">';
                }
            }
            ?>
            <div class="clearfix m-10-0 ">
                <?php
                foreach($this->property as $k=>$v){
                    if(!empty($v["img_file"]) && $v["img_type"]!=1){

                        echo '<img class="col-md-6 m-10-0" src="'.$this->basepath().'/images/files/thumbnail/'.$v["img_file"].'" alt="...">';
                    }
                }
                ?>
            </div>
        </aside>
    </div>
</div>
<div class="image-preview">

</div>


<script>
    var pathArrayTemp = <?php if(!empty($polygon)) echo $polygon; else echo '[]'; ?>;
    var areaTemp = null;
    var map = null;

    function initialize() {
        center = null;
        if(pathArrayTemp.length>0){
            center = new google.maps.LatLng(pathArrayTemp[0].lat, pathArrayTemp[0].lon);
        }else{
            center = new google.maps.LatLng(11.549608, 104.912727);
        }
        console.log(center);
        var mapOptions = {
            center: center,
            zoom: 16,
            mapTypeId: google.maps.MapTypeId.SATELLIT
        };

        map = new google.maps.Map(document.getElementById('map-canvas'),
            mapOptions);

        var drawingManager = new google.maps.drawing.DrawingManager({
            drawingMode: google.maps.drawing.OverlayType.MARKER,
            drawingControl: true,
            drawingControlOptions: {
                position: google.maps.ControlPosition.TOP_LEFT,
                drawingModes: []
            }
        });
        drawingManager.setMap(map);

        // Define the LatLng coordinates for the polygon.
        var triangleCoords = [];

        $(pathArrayTemp).each(function(k,v){
            triangleCoords.push(new google.maps.LatLng(v.lat, v.lon));
        });

        var distance = google.maps.geometry.spherical.computeDistanceBetween(new google.maps.LatLng(11.549876, 104.913269), new google.maps.LatLng(11.549618, 104.913283));

        console.log(distance);

        // Construct the polygon.
        bermudaTriangle = new google.maps.Polygon({
            paths: triangleCoords,
            strokeColor: '#FF0000',
            strokeOpacity: 0.8,
            strokeWeight: 3,
            fillColor: '#FF0000',
            fillOpacity: 0.35
        });

        bermudaTriangle.setMap(map);

        pathArrayTemp = bermudaTriangle.getPaths();
        areaTemp = google.maps.geometry.spherical.computeArea(triangleCoords);
        // console.log(areaTemp);

    }

    google.maps.event.addDomListener(window, 'load', initialize);

    $('.gallery').gallery();

</script>
