<?php
$p = $this->properties;
?>
<div>
    <h2 class="font-24 br-b-yeello p-15-0 no-margin">Recently Added
        <span class="pull-right font-13">
            <a class="m-10-0" href="<?php echo $this->basepath(); ?>/all-property"><i class="glyphicon glyphicon-th-list"></i> View all</a>
            <?php if(\Application\Controller\Permission::getPermission()==true): ?>
                <label> | </label>
                <a class="" href="<?php echo $this->basepath();?>/addnew"><i class="glyphicon glyphicon-plus"></i> Add New</a>
            <?php endif;?>
        </span>
    </h2>
    <div class="full-w no-padding p-15-0">
    <?php for($i=0; $i<count($p); $i=$i+2):?>
        <div class="clearfix">
            <aside class="col-md-6 no-padding prop-panel">
            <div class="media col-md-12 no-padding">
                <h4 class="c-blue p-b-10"><a href="<?php echo $this->basepath() ."/detail?pid=" .$p[$i]["property_id"];?>"><?php echo $p[$i]["prop_name"]; ?></a></h4>
                <div class="img" href="<?php echo $this->basepath();?>/detail?pid=<?php echo $p[$i]["property_id"];?>">
                    <a class="clearfix" href="<?php echo $this->basepath() ."/detail?pid=" .$p[$i]["property_id"];?>">
                    <?php if($p[$i]["img_file"]!=""): ?>
                    <img width="100%" class="media-object" src="<?php echo $this->basepath(); ?>/images/files/thumbnail/<?php echo $p[$i]["img_file"] ?>" alt="...">
                    <?php else: ?>
                    <img width="100%" class="media-object" src="<?php echo $this->basepath(); ?>/img/default-img.png" alt="...">
                    <?php endif;?>
                    </a>
                    <?php if(\Application\Controller\Permission::getPermission()): ?>
                        <div class="p-5-0 small pull-left clearfix">
                            <a class="pull-left p-0-5" href="<?php echo $this->basepath();?>/edit?pid=<?php echo $p[$i]["property_id"]; ?>"> <i class="glyphicon glyphicon-pencil"></i> Edit </a>
                            <span class=" pull-left p-0-5" style="margin-top:-3px;"> | </span>
                            <a class="pull-left p-0-5 delete" href="#" data-id="<?php echo $p[$i]["property_id"]; ?>"> <i class="glyphicon glyphicon-remove"></i> Remove </a>
                        </div>
                    <?php endif; ?>
                </div>
                <summary open="open" >
                    <article class="row">
                        <label class="col-md-5">Code Number</label>
                        <span class="col-md-7">: <?php echo $p[$i]["prop_code"]; ?></span>
                    </article>
                    <article class="row">
                        <label class="col-md-5">Province/City</label>
                        <span class="col-md-7">: <?php echo $p[$i]["prov_name"]; ?></span>
                    </article>
                    <article class="row">
                        <label class="col-md-5">Location</label>
                        <span class="col-md-7">: <?php echo $p[$i]["prop_location"]; ?></span>
                    </article>
                    <article class="row">
                        <label class="col-md-5">Land dimension</label>
                        <span class="col-md-7">: <?php echo $p[$i]["prop_dimension"]; ?></span>
                    </article>
                    <article class="row">
                        <label class="col-md-5">Size of land</label>
                        <span class="col-md-7">: <?php echo $p[$i]["prop_size"]; ?> sqm</span>
                    </article>
                    <article class="row">
                        <label class="col-md-5">Price </label>
                        <span class="col-md-7">: $ <?php echo $p[$i]["price_market"]; ?></span>
                    </article>
                </summary>
            </div>
        </aside>
            <?php if(isset($p[$i+1]["property_id"])):?>
            <aside class="col-md-6 no-padding prop-panel">
                <div class="media col-md-12 no-padding">
                    <h4 class="c-blue p-b-10"><a href="<?php echo $this->basepath() ."/detail?pid=" .$p[$i+1]["property_id"];?>"><?php echo $p[$i+1]["prop_name"]; ?></a></h4>
                    <div class="img" href="<?php echo $this->basepath();?>/detail?pid=<?php echo $p[$i+1]["property_id"];?>">
                        <a class="clearfix" href="<?php echo $this->basepath() ."/detail?pid=" .$p[$i+1]["property_id"];?>">
                        <?php if($p[$i+1]["img_file"]!=""): ?>
                            <img width="100%" class="media-object" src="<?php echo $this->basepath(); ?>/images/files/thumbnail/<?php echo $p[$i+1]["img_file"] ?>" alt="...">
                        <?php else: ?>
                            <img width="100%" class="media-object" src="<?php echo $this->basepath(); ?>/img/default-img.png" alt="...">
                        <?php endif;?>
                        </a>
                        <?php if(\Application\Controller\Permission::getPermission()): ?>
                            <div class="p-5-0 small pull-left clearfix">
                                <a class="pull-left p-0-5" href="<?php echo $this->basepath();?>/edit?pid=<?php echo $p[$i+1]["property_id"]; ?>"> <i class="glyphicon glyphicon-pencil"></i> Edit </a>
                                <span class=" pull-left p-0-5" style="margin-top:-3px;"> | </span>
                                <a class="pull-left p-0-5 delete" href="#" data-id="<?php echo $p[$i+1]["property_id"]; ?>"> <i class="glyphicon glyphicon-remove"></i> Remove </a>
                            </div>
                        <?php endif; ?>
                    </div>
                    <summary open="open" >
                        <article class="row">
                            <label class="col-md-5">Code Number</label>
                            <span class="col-md-7">: <?php echo $p[$i+1]["prop_code"]; ?></span>
                        </article>
                        <article class="row">
                            <label class="col-md-5">Province/City</label>
                            <span class="col-md-7">: <?php echo $p[$i+1]["prov_name"]; ?></span>
                        </article>
                        <article class="row">
                            <label class="col-md-5">Location</label>
                            <span class="col-md-7">: <?php echo $p[$i+1]["prop_location"]; ?></span>
                        </article>
                        <article class="row">
                            <label class="col-md-5">Land dimension</label>
                            <span class="col-md-7">: <?php echo $p[$i+1]["prop_dimension"]; ?></span>
                        </article>
                        <article class="row">
                            <label class="col-md-5">Size of land</label>
                            <span class="col-md-7">: <?php echo $p[$i+1]["prop_size"]; ?> sqm</span>
                        </article>
                        <article class="row">
                            <label class="col-md-5">Price </label>
                            <span class="col-md-7">: $ <?php echo $p[$i+1]["price_market"]; ?></span>
                        </article>
                    </summary>
                </div>
            </aside>
            <?php endif; ?>
        </div>
    <?php endfor; ?>
    </div>
</div>

<script>
    var baseUrl = '<?php echo $this->basepath(); ?>';
    $('.delete').click(function(){
        if(confirm('Do you want to delete this property?')){
            id = $(this).attr('data-id');
            var _this = this;
            $.ajax({
                url: baseUrl + '/property/' + id,
                type: 'DELETE',
                success: function(){
                    $(_this).parents('.prop-panel').fadeOut(500, function(){
                        $(_this).remove();
                    });
                }
            });
        }
        return false;
    });
</script>