<?php
use Application\Controller\Permission;
Permission::getPermission();
$p = \Zend\Stdlib\ArrayUtils::iteratorToArray($this->paginator);

?>
<div>
    <h2 class="font-24 br-b-yeello p-15-0 no-margin">All Properties

        <span class="pull-right font-13 p-10-0">
            <a href="<?php echo $this->basepath(); ?>/"><i class="glyphicon glyphicon-home"></i> Home </a>
            <label> | </label>
            <a href="<?php echo $this->basepath(); ?>/all-property"><i class="glyphicon glyphicon-th-list"></i> View all </a>
            <?php if(Permission::getPermission()==true): ?>
            <label> | </label>
            <a class="" href="<?php echo $this->basepath();?>/addnew"><i class="glyphicon glyphicon-plus"></i> Add New</a>
            <?php endif;?>
        </span>
        <?php if(!empty($this->propSessionId)):?>
        <span class="label label-success font-13 pull-right m-10">A property was <?php echo $this->action; ?>d.</span>
        <?php endif;?>
    </h2>
    <div class="full-w no-padding p-15-0 clearfix">
        <div class="col-md-3 no-padding-left">
            <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
                <div class="panel panel-default">
                    <div class="panel-heading" role="tab" id="headingOne">
                        <h4 class="panel-title">
                            <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                                Provinces
                            </a>
                        </h4>
                    </div>
                    <div id="collapseOne" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="headingOne">
                        <div class="panel-body">
                            <ul class="nav nav-pills" role="tablist">
                                <li role="presentation" class="<?php if($this->provinceId =="") echo "active"; ?> full-w"><a class="display-block" href="<?php echo $this->basepath("/all-property?s=".$this->search);?>" >All provinces</a></li>
                                <?php foreach($this->provinces as $k=>$v): ?>
                                <li role="presentation" class="full-w <?php if($this->provinceId ==$k) echo "active"; ?>"><a href="<?php echo $this->basepath("/all-property")."?s=".$this->search."&prov=".$k;?>"><?php echo $v; ?></a></li>
                                <?php endforeach; ?>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-9 no-padding-right">

            <?php for($i=0; $i<count($p); $i=$i+2):?>
                <div class="clearfix">
                <aside class="cover-madia col-md-6 prop-panel m-15-0 <?php if($p[$i]["property_id"] == $this->addedProp) echo "selected"; ?>">
                    <div class="media col-md-12 no-padding">
                        <h4 class="c-blue p-b-10">
                            <a class="img" href="<?php echo $this->basepath();?>/detail?pid=<?php echo $p[$i]["property_id"] ."&page=" .$this->page;?>">
                                <?php if($p[$i]["property_id"] == $this->addedProp): ?>
                                <i class="glyphicon glyphicon-bookmark c-red font-13"></i>
                                <?php endif; ?>
                                <?php echo $p[$i]["prop_name"];
                                ?>
                            </a>
                        </h4>
                        <div class="img">
                            <a class="clearfix" href="<?php echo $this->basepath() ."/detail?pid=" .$p[$i]["property_id"]."&page=".$this->page;?>">
                            <?php if($p[$i]["img_file"]!=""): ?>
                                <img width="100%" class="media-object" src="<?php echo $this->basepath(); ?>/images/files/thumbnail/<?php echo $p[$i]["img_file"] ?>" alt="...">
                            <?php else: ?>
                                <img width="100%" class="media-object" src="<?php echo $this->basepath(); ?>/img/default-img.png" alt="...">
                            <?php endif;?>
                            </a>
                            <?php if(Permission::getPermission()):?>
                            <div class="p-5-0 small pull-left clearfix">
                                <a class="pull-left p-0-5" href="<?php echo $this->basepath();?>/edit?pid=<?php echo $p[$i]["property_id"] ."&page=" .$this->page;  ?>"> <i class="glyphicon glyphicon-pencil"></i> Edit </a>
                                <span class=" pull-left p-0-5" style="margin-top:-3px;"> | </span>
                                <a class="pull-left p-0-5 delete" href="#" data-id="<?php echo $p[$i]["property_id"]; ?>"> <i class="glyphicon glyphicon-remove"></i> Remove </a>
                            </div>
                            <?php endif; ?>
                        </div>
                        <summary open="open" >
                            <article class="row">
                                <label class="col-md-5">Code Number</label>
                                <span class="col-md-7">: <?php echo $p[$i]["prop_code"]; ?></span>
                            </article>
                            <article class="row">
                                <label class="col-md-5">Province/City</label>
                                <span class="col-md-7">: <?php echo $p[$i]["prov_name"]; ?></span>
                            </article>
                            <article class="row">
                                <label class="col-md-5">Location</label>
                                <span class="col-md-7">: <?php echo $p[$i]["prop_location"]; ?></span>
                            </article>
                            <article class="row">
                                <label class="col-md-5">Land dimension</label>
                                <span class="col-md-7">: <?php echo $p[$i]["prop_dimension"]; ?></span>
                            </article>
                            <article class="row">
                                <label class="col-md-5">Size of land</label>
                                <span class="col-md-7">: <?php echo $p[$i]["prop_size"]; ?> sqm</span>
                            </article>
                            <article class="row">
                                <label class="col-md-5">Price </label>
                                <span class="col-md-7">: $ <?php echo $p[$i]["price_market"]; ?></span>
                            </article>
                        </summary>

                    </div>
                </aside>


                <?php if(isset($p[$i+1]["property_id"])):?>
                    <aside class="cover-madia col-md-6 prop-panel m-15-0 <?php if($p[$i+1]["property_id"] == $this->addedProp) echo "selected"; ?>">
                        <div class="media col-md-12 no-padding">
                            <h4 class="c-blue p-b-10">
                                <a class="img" href="<?php echo $this->basepath();?>/detail?pid=<?php echo $p[$i+1]["property_id"] ."&page=" .$this->page;?>">
                                    <?php if($p[$i+1]["property_id"] == $this->addedProp): ?>
                                        <i class="glyphicon glyphicon-bookmark c-red font-13"></i>
                                    <?php endif; ?>
                                    <?php echo $p[$i+1]["prop_name"]; ?>

                                </a>
                            </h4>
                            <div class="img">
                                <a class="clearfix" href="<?php echo $this->basepath() ."/detail?pid=" .$p[$i+1]["property_id"]."&page=".$this->page;?>">
                                <?php if($p[$i+1]["img_file"]!=""): ?>
                                    <img width="100%" class="media-object" src="<?php echo $this->basepath(); ?>/images/files/thumbnail/<?php echo $p[$i+1]["img_file"] ?>" alt="...">
                                <?php else: ?>
                                    <img width="100%" class="media-object" src="<?php echo $this->basepath(); ?>/img/default-img.png" alt="...">
                                <?php endif;?>
                                </a>
                                <?php if(Permission::getPermission()):?>
                                    <div class="p-5-0 small pull-left clearfix">
                                        <a class="pull-left p-0-5" href="<?php echo $this->basepath();?>/edit?pid=<?php echo $p[$i+1]["property_id"] ."&page=" .$this->page;  ?>"> <i class="glyphicon glyphicon-pencil"></i> Edit </a>
                                        <span class=" pull-left p-0-5" style="margin-top:-3px;"> | </span>
                                        <a class="pull-left p-0-5 delete" href="#" data-id="<?php echo $p[$i+1]["property_id"]; ?>"> <i class="glyphicon glyphicon-remove"></i> Remove </a>
                                    </div>
                                <?php endif; ?>
                            </div>
                            <summary open="open" >
                                <article class="row">
                                    <label class="col-md-5">Code Number</label>
                                    <span class="col-md-7">: <?php echo $p[$i+1]["prop_code"]; ?></span>
                                </article>
                                <article class="row">
                                    <label class="col-md-5">Province/City</label>
                                    <span class="col-md-7">: <?php echo $p[$i+1]["prov_name"]; ?></span>
                                </article>
                                <article class="row">
                                    <label class="col-md-5">Location</label>
                                    <span class="col-md-7">: <?php echo $p[$i+1]["prop_location"]; ?></span>
                                </article>
                                <article class="row">
                                    <label class="col-md-5">Land dimension</label>
                                    <span class="col-md-7">: <?php echo $p[$i+1]["prop_dimension"]; ?></span>
                                </article>
                                <article class="row">
                                    <label class="col-md-5">Size of land</label>
                                    <span class="col-md-7">: <?php echo $p[$i+1]["prop_size"]; ?> sqm</span>
                                </article>
                                <article class="row">
                                    <label class="col-md-5">Price </label>
                                    <span class="col-md-7">: $ <?php echo $p[$i+1]["price_market"]; ?></span>
                                </article>
                            </summary>

                        </div>
                    </aside>

                <?php endif; ?>
                </div>
            <?php endfor; ?>
        </div>

    </div>
    <div class="text-center clearfix display-block"> <?php echo $this->paginationControl($this->paginator,'sliding',array('layout/_paginator.phtml','viewmore'),array('controller' => 'Index','category'=>$this->category));?> </div>
</div>
<script>
    var baseUrl = '<?php echo $this->basepath(); ?>';
    $('.delete').click(function(){
        if(confirm('Do you want to delete this property?')){
            id = $(this).attr('data-id');
            var _this = this;
            $.ajax({
                url: baseUrl + '/property/' + id,
                type: 'DELETE',
                success: function(){
                    $(_this).parents('.prop-panel').fadeOut(500, function(){
                        $(this).remove();
                    });
                }
            });
        }
    });
</script>
